# Generated by Django 5.2.17 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'customer_type__in': ['Seller', 'Landlord']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.customer'),
        ),
    ]
