# Generated by Django 5.2.17 on 2026-09-22 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_property_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_code', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('inquiry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('message', models.TextField(blank=True, verbose_name='Message / notes')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Viewing', 'Viewing'), ('Negotiation', 'Negotiation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='core.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='core.property')),
            ],
            options={
                'ordering': ['-inquiry_date', '-created_at', '-pk'],
            },
        ),
    ]
