# Generated by Django 5.2.17 on 2026-09-22 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('appointment_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.property')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time', '-pk'],
            },
        ),
    ]
